name: Deploy
on:
  push:
    branches:
    - main

jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.10.0

    - name: Install dependencies
      run: npm install

    - name: Create .env (environment variables file)
      run: >
        node
        --import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
        .github/createEnviron.ts
        --BASE_PATH ${{ secrets.BASE_PATH }}
        --ASSETS_URL ${{ secrets.ASSETS_URL }}
        --PUBLIC_SITE_URL ${{ secrets.ASSETS_URL }}

    - name: Build app
      run: npm run build

    - name: Deploy
      uses: SamKirkland/FTP-Deploy-Action@2.0.0
      env:
        FTP_SERVER: ${{ secrets.HOST }}
        FTP_USERNAME: ${{ secrets.USERNAME }}
        FTP_PASSWORD: ${{ secrets.PASSWORD }}
        METHOD: ${{ secrets.PROTOCOL }}
        LOCAL_DIR: build
        REMOTE_DIR: ${{ secrets.REMOTE_PATH }}
        ARGS: --delete --parallel=10
